cc_library(
    name = "aoc_day",
    hdrs = ["AoCDay.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "utils",
    hdrs = ["utils.hpp"],
    visibility = ["//visibility:public"],
)
